import {useState} from 'react'
import {Link,NavLink,useNavigate} from 'react-router-dom'
import {Heart,Menu,Moon,Search,ShoppingBag,Sun,User,X} from 'lucide-react'
import {useStore} from '../store/StoreContext'
export const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(n)
export function Layout({children}){const{cart,wishlist,dark,setDark,toasts}=useStore(),[menu,setMenu]=useState(false),[q,setQ]=useState(''),navigate=useNavigate(),count=cart.reduce((s,x)=>s+x.qty,0);const search=e=>{e.preventDefault();navigate(`/shop?q=${encodeURIComponent(q)}`);setMenu(false)};return <div className="app-shell">
  <div className="announcement">Complimentary delivery over $150 <span>•</span> 30-day considered returns</div>
  <header><Link className="brand" to="/">Saamaan<span>Har Chiez, Dil sa Chunan</span></Link><nav className={menu?'open':''}><button className="nav-close icon" onClick={()=>setMenu(false)} aria-label="Close menu"><X/></button>{[['/shop','Shop'],['/stores','Makers'],['/about','Our standard']].map(([to,t])=><NavLink key={to} to={to} onClick={()=>setMenu(false)}>{t}</NavLink>)}<NavLink to="/seller">Sell on Saaman</NavLink></nav>
  <form className="header-search" onSubmit={search}><Search size={18}/><input aria-label="Search products" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search the collection"/></form>
  <div className="actions"><button className="icon" onClick={()=>setDark(!dark)} aria-label="Toggle theme">{dark?<Sun/>:<Moon/>}</button><Link className="icon badge" to="/wishlist" aria-label="Wishlist"><Heart/><b>{wishlist.length}</b></Link><Link className="icon" to="/account" aria-label="Account"><User/></Link><Link className="icon badge" to="/cart" aria-label="Shopping bag"><ShoppingBag/><b>{count}</b></Link><button className="icon hamburger" onClick={()=>setMenu(true)} aria-label="Open menu"><Menu/></button></div></header>
  <main>{children}</main><footer><div><Link className="brand light" to="/">Saamaan<span>Har Chiez, Dil sa Chunan</span></Link><p>A marketplace for considered objects, independent makers, and better everyday rituals.</p></div><div><h4>Discover</h4><Link to="/shop">New arrivals</Link><Link to="/stores">Our makers</Link><Link to="/shop?sort=rating">Best reviewed</Link></div><div><h4>Customer care</h4><Link to="/account">Delivery & orders</Link><Link to="/account">Returns</Link><Link to="/about">Our standard</Link></div><div><h4>Keep in touch</h4><p>Monthly stories, objects and studio visits.</p><div className="newsletter"><input aria-label="Email" placeholder="Email address"/><button>Join</button></div></div></footer><div className="toast-stack" aria-live="polite">{toasts.map(t=><div className="toast" key={t.id}>{t.message}</div>)}</div></div>}
